base: 'https://femanager10.ddev.site/'
baseVariants: {  }
errorHandling: {  }
languages:
  -
    title: english
    enabled: true
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    websiteTitle: english
    navigationTitle: en
    hreflang: en-US
    direction: ''
    flag: global
    languageId: '0'
rootPageId: 1
routes: {  }
websiteTitle: femanager
